package com.ljf.greendao.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ljf.greendao.Animal;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANIMAL".
*/
public class AnimalDao extends AbstractDao<Animal, Void> {

    public static final String TABLENAME = "ANIMAL";

    /**
     * Properties of entity Animal.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", false, "NAME");
        public final static Property Age = new Property(1, int.class, "age", false, "AGE");
        public final static Property Gender = new Property(2, String.class, "gender", false, "GENDER");
    }


    public AnimalDao(DaoConfig config) {
        super(config);
    }
    
    public AnimalDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANIMAL\" (" + //
                "\"NAME\" TEXT," + // 0: name
                "\"AGE\" INTEGER NOT NULL ," + // 1: age
                "\"GENDER\" TEXT);"); // 2: gender
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANIMAL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Animal entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
        stmt.bindLong(2, entity.getAge());
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(3, gender);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Animal entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
        stmt.bindLong(2, entity.getAge());
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(3, gender);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Animal readEntity(Cursor cursor, int offset) {
        Animal entity = new Animal( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // name
            cursor.getInt(offset + 1), // age
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // gender
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Animal entity, int offset) {
        entity.setName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAge(cursor.getInt(offset + 1));
        entity.setGender(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Animal entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Animal entity) {
        return null;
    }

    @Override
    public boolean hasKey(Animal entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
