package com.ljf.greendao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ljf.greendao.Animal;

import com.ljf.greendao.greendao.AnimalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig animalDaoConfig;

    private final AnimalDao animalDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        animalDaoConfig = daoConfigMap.get(AnimalDao.class).clone();
        animalDaoConfig.initIdentityScope(type);

        animalDao = new AnimalDao(animalDaoConfig, this);

        registerDao(Animal.class, animalDao);
    }
    
    public void clear() {
        animalDaoConfig.clearIdentityScope();
    }

    public AnimalDao getAnimalDao() {
        return animalDao;
    }

}
